services:
  minecraft:
    container_name: PaperMC
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    env_file:
      - .env
    volumes:
      - ./extras:/extras
      - ./data:/data
